#server configuration
server:
  port : 9008
  servlet:
    encoding:
      force-response: true

#datasource configurations`
datasource:
  primary:
    jdbc-url: jdbc:sqlserver://192.168.41.71:1433;databaseName=transfer_recall_v2
    username: sa
    password: t3@mApt
    testOnBorrow: true
    validation-query: SELECT 1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect

  infopool:
      jdbc-url: jdbc:sqlserver://10.10.7.83:1433;databaseName=Ebanking
      username: ebanking_connect_user
      password: Password@123
      testOnBorrow: true
      validation-query: SELECT 1
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect

  finacle:
    jdbc-url: jdbc:oracle:thin:@10.120.9.21:1521:FBDB_STDBY2
    username: profectus_fin
    password: Fidelity_12
    testOnBorrow: true
    validation-query: SELECT 1 from dual
    driver-class-name: oracle.jdbc.OracleDriver

#logging properties
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

    root: INFO

    type:
      descriptor:
        sql:
        BasicBinder: TRACE

  file:
    name: /Users/aosobu/Documents/ProjectTeamApt/fidelity/transfer-recall/logs/transfer-recall

#cba configurations
finacle:
  htd:
    table: tbaadm.htd
  dtd:
    table: tbaadm.dtd
  gam:
    table: tbaadm.gam
  upr:
    table: tbaadm.upr
  get:
    table: tbaadm.get
  gsp:
    table: tbaadm.gsp

#flyway configuration
flyway:
  jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=transfer_recall
  username: sa
  password: Sam2019$
  locations: /Users/aosobu/Documents/ProjectTeamApt/fidelity/transfer-recall/src/main/resources/db/migration

#default spring datasource configurations
spring:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

      databse-platform: org.hibernate.dialect.MySQL5InnoDBDialect

      data:
        jpa:
          repositories:
            bootstrap-mode: deferred
  flyway:
      enabled: true

default:
  statistics:
    passed:
      days: 7

hibernate:
  dialect:

tracking:
  number:
    length: 10

complaint:
  file:
    path: uploads/complaints

oauth:
  resource:
    id: autum-settlement-service

  verifier:
    key: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAskW18478JOqsJretRDk8I2R97e34qgwUt9DM3AAZdaskiL2ygZfCTumYY90tjvvU3ypZcNvvtrJ54g+utCTdfzIPmFIQzMD83zbONd4YctI+7a0yqzQ8GZUKgvdcsj2DQ0GqtsKm6yJ21VLJr9PIaGRjp67/9Wi6PCg0IJLBH0NNsO4NhdtPK804zgB0VZlJuWRBM1Iu0NC6OKmmKogYDnQfzvdFXGWpcF/1Thf/9cTIW+BTOG0Kf5DQrs/MMv1CWSTiFvmFchMl7OrkFMQqqMx0FsAz3ZF49+N3HYAISUPbdjWScYOBPUZzj+p19Sw2fSEHQlLFM/Au3/GC3tzeXQIDAQAB\n-----END PUBLIC KEY-----




